"""
Incident Report Renderer

Converts a Report model into a polished Markdown document.

Author: Mahesh Kolekar
Project: Backup Failure Triage Agent
"""

from __future__ import annotations

from models.report import Report


def render_markdown_report(report: Report) -> str:
    """
    Render a Report model as a Markdown document.
    """

    incident = report.incident
    remediation = report.remediation

    lines: list[str] = []

    lines.append(f"# Incident Report — {report.report_id}")
    lines.append("")
    lines.append(f"**Generated:** {report.generated_at:%Y-%m-%d %H:%M:%S} UTC")
    lines.append(f"**Generated By:** {report.generated_by}")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append(report.executive_summary)
    lines.append("")
    lines.append("## Business Impact")
    lines.append(report.business_impact)
    lines.append("")
    lines.append("## Technical Details")
    lines.append(f"- **Backup Job:** {incident.backup_job}")
    lines.append(f"- **VM Name:** {incident.vm_name or 'Unknown'}")
    lines.append(f"- **Repository:** {incident.repository or 'Unknown'}")
    lines.append(f"- **Error Code:** {incident.error_code or 'Unknown'}")
    lines.append(f"- **Severity:** {incident.severity}")
    lines.append(f"- **Confidence:** {incident.confidence:.0%}")
    lines.append("")
    lines.append("## Root Cause")
    lines.append(incident.root_cause)
    lines.append("")

    if incident.evidence:
        lines.append("## Evidence")
        for item in incident.evidence:
            lines.append(f"- {item.description}")
        lines.append("")

    lines.append("## Recommended Actions")
    lines.append(remediation.recommendation)
    lines.append("")

    if remediation.engineer_checklist:
        lines.append("### Engineer Checklist")
        for step in remediation.engineer_checklist:
            lines.append(f"{step.step_number}. {step.description}")
        lines.append("")

    if remediation.powershell_script:
        lines.append("### PowerShell Script")
        lines.append(f"`{remediation.powershell_script.filename}`")
        lines.append("")
        lines.append("```powershell")
        lines.append(remediation.powershell_script.content)
        lines.append("```")
        lines.append("")

    lines.append("## Estimated Downtime")
    lines.append(remediation.estimated_downtime)
    lines.append("")
    lines.append("## SLA Risk")
    lines.append(report.sla_risk)
    lines.append("")
    lines.append("## Next Steps")
    lines.append(report.recommendations or "None specified.")
    lines.append("")
    lines.append(
        f"**Human Approval Required:** "
        f"{'Yes' if remediation.requires_human_approval else 'No'}"
    )

    return "\n".join(lines)