"""
Report Model

Defines the final incident report generated by the
Report Agent.

Author: Mahesh Kolekar
Project: Backup Failure Triage Agent
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field

from models.incident import Incident
from models.remediation import Remediation


class Report(BaseModel):
    """
    Final incident report.
    """

    report_id: str = Field(
        ...,
        description="Unique report identifier."
    )

    incident: Incident = Field(
        ...,
        description="Incident analysis details."
    )

    remediation: Remediation = Field(
        ...,
        description="Remediation plan."
    )

    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Report generation timestamp."
    )

    generated_by: str = Field(
        default="Backup Failure Triage Agent",
        description="Application that generated the report."
    )

    report_format: str = Field(
        default="markdown",
        description="markdown, json or pdf"
    )

    executive_summary: str = Field(
        ...,
        description="Short summary for management."
    )

    business_impact: str = Field(
        ...,
        description="Potential business impact."
    )

    sla_risk: str = Field(
        default="Unknown",
        description="SLA impact assessment."
    )

    estimated_resolution_time: str = Field(
        default="Unknown",
        description="Estimated resolution time."
    )

    recommendations: Optional[str] = Field(
        default=None,
        description="Additional recommendations."
    )

    class Config:
        json_schema_extra = {
            "example": {
                "report_id": "RPT-20260703-001",
                "generated_by": "Backup Failure Triage Agent",
                "report_format": "markdown",
                "executive_summary": (
                    "Daily backup failed because the repository "
                    "was out of available storage."
                ),
                "business_impact": (
                    "Production backups were not completed, "
                    "increasing the risk of data loss."
                ),
                "sla_risk": "High",
                "estimated_resolution_time": "15 minutes",
                "recommendations": (
                    "Increase repository capacity and "
                    "monitor storage utilization."
                )
            }
        }